{
 "title": "Experiment Overview - SQLite",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "run",
    "query": "SELECT DISTINCT run_name\nfrom metrics;"
   }
  ]
 },
 "panels": [
  {
   "title": "Validation Loss",
   "type": "trend",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_iterations' THEN value END) AS num_iterations,\n    LEAD(MAX(CASE WHEN metric_name = 'val_loss' THEN value END)) \n      OVER (ORDER BY timestamp) AS val_loss\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_iterations', 'val_loss')\n    AND metric_type = 'iteration'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_iterations, val_loss\nFROM grouped_metrics\nWHERE num_iterations IS NOT NULL\nORDER BY num_iterations ASC\n",
     "rawQueryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_iterations' THEN value END) AS num_iterations,\n    LEAD(MAX(CASE WHEN metric_name = 'val_loss' THEN value END)) \n      OVER (ORDER BY timestamp) AS val_loss\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_iterations', 'val_loss')\n    AND metric_type = 'iteration'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_iterations, val_loss\nFROM grouped_metrics\nWHERE num_iterations IS NOT NULL\nORDER BY num_iterations ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Ratio Proven",
   "type": "trend",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "queryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_iterations' THEN value END) AS num_iterations,\n    LEAD(MAX(CASE WHEN metric_name = 'ratio_proven' THEN value END)) \n      OVER (ORDER BY timestamp) AS ratio_proven\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_iterations', 'ratio_proven')\n    AND metric_type = 'iteration'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_iterations, ratio_proven\nFROM grouped_metrics\nWHERE num_iterations IS NOT NULL\nORDER BY num_iterations ASC\n",
     "rawQueryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_iterations' THEN value END) AS num_iterations,\n    LEAD(MAX(CASE WHEN metric_name = 'ratio_proven' THEN value END)) \n      OVER (ORDER BY timestamp) AS ratio_proven\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_iterations', 'ratio_proven')\n    AND metric_type = 'iteration'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_iterations, ratio_proven\nFROM grouped_metrics\nWHERE num_iterations IS NOT NULL\nORDER BY num_iterations ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Mean logprobs of solution of hard problem",
   "type": "trend",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "queryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_iterations' THEN value END) AS num_iterations,\n    LEAD(MAX(CASE WHEN metric_name = 'mean_hard_sol_log_probs' THEN value END)) \n      OVER (ORDER BY timestamp) AS mean_hard_sol_log_probs\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_iterations', 'mean_hard_sol_log_probs')\n    AND metric_type = 'iteration'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_iterations, mean_hard_sol_log_probs\nFROM grouped_metrics\nWHERE num_iterations IS NOT NULL\nORDER BY num_iterations ASC\n",
     "rawQueryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_iterations' THEN value END) AS num_iterations,\n    LEAD(MAX(CASE WHEN metric_name = 'mean_hard_sol_log_probs' THEN value END)) \n      OVER (ORDER BY timestamp) AS mean_hard_sol_log_probs\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_iterations', 'mean_hard_sol_log_probs')\n    AND metric_type = 'iteration'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_iterations, mean_hard_sol_log_probs\nFROM grouped_metrics\nWHERE num_iterations IS NOT NULL\nORDER BY num_iterations ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Progress Loss",
   "type": "trend",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_steps' THEN value END) AS num_steps,\n    LEAD(MAX(CASE WHEN metric_name = 'progress_loss' THEN value END)) \n      OVER (ORDER BY timestamp) AS progress_loss\n  FROM metrics\n  WHERE run_name IN ('mcts-val-mu-0_001-threshold-0_2-1','mcts-val-mu-0_001-threshold-0_2-10','mcts-val-mu-0_001-threshold-0_2-2','mcts-val-mu-0_001-threshold-0_2-3','mcts-val-mu-0_001-threshold-0_2-4','mcts-val-mu-0_001-threshold-0_2-5','mcts-val-mu-0_001-threshold-0_2-6','mcts-val-mu-0_001-threshold-0_2-7','mcts-val-mu-0_001-threshold-0_2-8','mcts-val-mu-0_001-threshold-0_2-9')\n    AND metric_name IN ('num_steps', 'progress_loss')\n    AND metric_type = 'step'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_steps, progress_loss\nFROM grouped_metrics\nWHERE num_steps IS NOT NULL\nORDER BY num_steps ASC\n",
     "rawQueryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_steps' THEN value END) AS num_steps,\n    LEAD(MAX(CASE WHEN metric_name = 'progress_loss' THEN value END)) \n      OVER (ORDER BY timestamp) AS progress_loss\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_steps', 'progress_loss')\n    AND metric_type = 'step'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_steps, progress_loss\nFROM grouped_metrics\nWHERE num_steps IS NOT NULL\nORDER BY num_steps ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Train Loss",
   "type": "trend",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "targets": [
    {
     "queryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_steps' THEN value END) AS num_steps,\n    LEAD(MAX(CASE WHEN metric_name = 'train_loss' THEN value END)) \n      OVER (ORDER BY timestamp) AS train_loss\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_steps', 'train_loss')\n    AND metric_type = 'step'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_steps, train_loss\nFROM grouped_metrics\nWHERE num_steps IS NOT NULL\nORDER BY num_steps ASC\n",
     "rawQueryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_steps' THEN value END) AS num_steps,\n    LEAD(MAX(CASE WHEN metric_name = 'train_loss' THEN value END)) \n      OVER (ORDER BY timestamp) AS train_loss\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_steps', 'train_loss')\n    AND metric_type = 'step'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_steps, train_loss\nFROM grouped_metrics\nWHERE num_steps IS NOT NULL\nORDER BY num_steps ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Loss",
   "type": "trend",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "targets": [
    {
     "queryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_steps' THEN value END) AS num_steps,\n    LEAD(MAX(CASE WHEN metric_name = 'loss' THEN value END)) \n      OVER (ORDER BY timestamp) AS loss\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_steps', 'loss')\n    AND metric_type = 'step'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_steps, loss\nFROM grouped_metrics\nWHERE num_steps IS NOT NULL\nORDER BY num_steps ASC\n",
     "rawQueryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_steps' THEN value END) AS num_steps,\n    LEAD(MAX(CASE WHEN metric_name = 'loss' THEN value END)) \n      OVER (ORDER BY timestamp) AS loss\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_steps', 'loss')\n    AND metric_type = 'step'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_steps, loss\nFROM grouped_metrics\nWHERE num_steps IS NOT NULL\nORDER BY num_steps ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Ratio of Difficulty-Problem Pairs",
   "type": "trend",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 8 },
   "targets": [
    {
     "queryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_steps' THEN value END) AS num_steps,\n    LEAD(MAX(CASE WHEN metric_name = 'ratio_diff_problem_pairs' THEN value END)) \n      OVER (ORDER BY timestamp) AS ratio_diff_problem_pairs\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_steps', 'ratio_diff_problem_pairs')\n    AND metric_type = 'step'\n  GROUP BY id, run_name, timestamp\n),\nnumbered_metrics AS (\n  SELECT \n    ROW_NUMBER() OVER (PARTITION BY run_name ORDER BY num_steps ASC) AS row_number,\n    run_name,\n    timestamp,\n    num_steps,\n    ratio_diff_problem_pairs\n  FROM grouped_metrics\n  WHERE num_steps IS NOT NULL\n)\nSELECT \n  run_name, \n  timestamp, \n  num_steps, \n  ratio_diff_problem_pairs\nFROM numbered_metrics\nWHERE row_number % 50 = 0\nORDER BY num_steps ASC;\n",
     "rawQueryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_steps' THEN value END) AS num_steps,\n    LEAD(MAX(CASE WHEN metric_name = 'ratio_diff_problem_pairs' THEN value END)) \n      OVER (ORDER BY timestamp) AS ratio_diff_problem_pairs\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_steps', 'ratio_diff_problem_pairs')\n    AND metric_type = 'step'\n  GROUP BY id, run_name, timestamp\n),\nnumbered_metrics AS (\n  SELECT \n    ROW_NUMBER() OVER (PARTITION BY run_name ORDER BY num_steps ASC) AS row_number,\n    run_name,\n    timestamp,\n    num_steps,\n    ratio_diff_problem_pairs\n  FROM grouped_metrics\n  WHERE num_steps IS NOT NULL\n)\nSELECT \n  run_name, \n  timestamp, \n  num_steps, \n  ratio_diff_problem_pairs\nFROM numbered_metrics\nWHERE row_number % 50 = 0\nORDER BY num_steps ASC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Final Goals Proven",
   "type": "trend",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "queryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_iterations' THEN value END) AS num_iterations,\n    LEAD(MAX(CASE WHEN metric_name = 'final_goals_proven' THEN value END)) \n      OVER (ORDER BY timestamp) AS final_goals_proven\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_iterations', 'final_goals_proven')\n    AND metric_type = 'iteration'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_iterations, final_goals_proven\nFROM grouped_metrics\nWHERE num_iterations IS NOT NULL\nORDER BY num_iterations ASC\n",
     "rawQueryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_iterations' THEN value END) AS num_iterations,\n    LEAD(MAX(CASE WHEN metric_name = 'final_goals_proven' THEN value END)) \n      OVER (ORDER BY timestamp) AS final_goals_proven\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_iterations', 'final_goals_proven')\n    AND metric_type = 'iteration'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_iterations, final_goals_proven\nFROM grouped_metrics\nWHERE num_iterations IS NOT NULL\nORDER BY num_iterations ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Mu",
   "type": "trend",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 16 },
   "targets": [
    {
     "queryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_steps' THEN value END) AS num_steps,\n    LEAD(MAX(CASE WHEN metric_name = 'mu' THEN value END)) \n      OVER (ORDER BY timestamp) AS mu\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_steps', 'mu')\n    AND metric_type = 'step'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_steps, mu\nFROM grouped_metrics\nWHERE num_steps IS NOT NULL\nORDER BY num_steps ASC\n",
     "rawQueryText": "WITH grouped_metrics AS (\n  SELECT \n    id,\n    run_name,\n    timestamp,\n    MAX(CASE WHEN metric_name = 'num_steps' THEN value END) AS num_steps,\n    LEAD(MAX(CASE WHEN metric_name = 'mu' THEN value END)) \n      OVER (ORDER BY timestamp) AS mu\n  FROM metrics\n  WHERE run_name IN (${run:sqlstring})\n    AND metric_name IN ('num_steps', 'mu')\n    AND metric_type = 'step'\n  GROUP BY id, run_name, timestamp\n)\nSELECT run_name, timestamp, num_steps, mu\nFROM grouped_metrics\nWHERE num_steps IS NOT NULL\nORDER BY num_steps ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}